// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

// MiniClosedFileFolderPicture.h
//
// Automatically generated by dump_image
// Generation date: Sat Jan  3 19:08:25 1998
//

#ifndef __MiniClosedFileFolderPicture_h
#define __MiniClosedFileFolderPicture_h

class MLImage;

class MiniClosedFileFolderPicture
{
protected:
  static const int width;
  static const int height;
  static unsigned char data[];
public:
  static MLImage* get();
};

#endif // ifndef __MiniClosedFileFolderPicture_h
