// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  LoadGeometryDlg.h
  Tue Sep  2 23:15:27 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __LoadGeometryDlg_h
#define __LoadGeometryDlg_h

class LoadGeometryDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
          Widget_1 = 1,
              size = 9,
         Widget_10 = 10,
              date = 11,
         Widget_12 = 12,
         Widget_13 = 13,
              user = 14,
           preview = 4,
          Widget_5 = 5,
          Widget_7 = 7,
          Widget_8 = 8,
          filename = 17,
     preview_stats = 18,
         databases = 2,
              list = 3,
    preview_switch = 6,
            cancel = 15,
                ok = 16
    };
};

#endif // ifndef __LoadGeometryDlg_h
