// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

// Automatically generated by dump_sphere.C
static const int width= 8;
static const int height= 8;
static const double data[192] = {
  // line 0 (0-7)
  0, 0, 0,
  0, 0, 0,
  120.952, 0.9, 0.27451,
  118.5, 1, 0.156863,
  118.333, 1, 0.141176,
  122.353, 0.962264, 0.207843,
  0, 0, 0,
  0, 0, 0,
  // line 1 (0-7)
  0, 0, 0,
  120, 0.968421, 0.372549,
  117.5, 1, 0.282353,
  115.862, 1, 0.227451,
  118.5, 1, 0.156863,
  118.125, 1, 0.12549,
  120, 0.972222, 0.141176,
  0, 0, 0,
  // line 2 (0-7)
  122.824, 0.702479, 0.47451,
  117.561, 1, 0.482353,
  117.561, 1, 0.482353,
  117.222, 1, 0.423529,
  117.805, 1, 0.321569,
  116.667, 1, 0.211765,
  116, 1, 0.117647,
  122.353, 0.962264, 0.207843,
  // line 3 (0-7)
  120, 0.987421, 0.623529,
  117.241, 1, 0.682353,
  117.193, 1, 0.670588,
  117.308, 1, 0.611765,
  117.5, 1, 0.470588,
  117.209, 1, 0.337255,
  116.667, 1, 0.211765,
  117.143, 1, 0.164706,
  // line 4 (0-7)
  120, 0.988439, 0.678431,
  117.379, 1, 0.807843,
  120, 0.940594, 0.792157,
  121.297, 0.91133, 0.796078,
  120, 1, 0.666667,
  117.273, 1, 0.517647,
  117.391, 1, 0.360784,
  117.778, 1, 0.211765,
  // line 5 (0-7)
  121.818, 0.727941, 0.533333,
  117.273, 1, 0.776471,
  120, 0.875622, 0.788235,
  117.333, 0.658537, 0.803922,
  118.8, 1, 0.784314,
  117.407, 1, 0.635294,
  117.458, 1, 0.462745,
  120, 0.651685, 0.34902,
  // line 6 (0-7)
  0, 0, 0,
  118.563, 0.976608, 0.670588,
  117.286, 1, 0.780392,
  118.507, 0.985294, 0.8,
  117.327, 1, 0.792157,
  117.273, 1, 0.690196,
  118.647, 0.970803, 0.537255,
  0, 0, 0,
  // line 7 (0-7)
  0, 0, 0,
  0, 0, 0,
  121.837, 0.725926, 0.529412,
  120, 0.988439, 0.678431,
  120, 0.988304, 0.670588,
  121.895, 0.719697, 0.517647,
  0, 0, 0,
  0, 0, 0,
  };
