// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  KBOpenDlg.h
  Sun Oct 26 18:17:24 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __KBOpenDlg_h
#define __KBOpenDlg_h

class KBOpenDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
       Widget_1 = 1,
       Widget_4 = 4,
       Widget_7 = 7,
       Widget_9 = 9,
       location = 10,
      Widget_13 = 13,
    directories = 2,
          files = 3,
      selection = 8,
             ok = 12,
         cancel = 11
    };
};

#endif // ifndef __KBOpenDlg_h
