// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  AlignDlg.h
  Thu Aug 22 23:58:20 1996

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __AlignDlg_h
#define __AlignDlg_h

class AlignDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[654];

  enum
    {
      Widget_12 = 12,
      Widget_11 = 11,
       Widget_5 = 5,
       Widget_6 = 6,
       Widget_7 = 7,
       Widget_8 = 8,
      vertAlign = 16,
            top = 1,
     vertCenter = 9,
         bottom = 4,
     horizAlign = 15,
           left = 3,
    horizCenter = 10,
          right = 2,
             ok = 14,
         cancel = 13
    };
};

#endif // ifndef __AlignDlg_h
