// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  CheckBoxDlg.h
  Thu Aug 22 23:58:25 1996

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __CheckBoxDlg_h
#define __CheckBoxDlg_h

class CheckBoxDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[617];

  enum
    {
    Widget_15 = 15,
        group = 10,
     Widget_8 = 8,
     Widget_9 = 9,
    Widget_14 = 14,
         text = 3,
         name = 6,
    available = 4,
         left = 7,
       center = 11,
        right = 12,
       margin = 13,
           ok = 2,
       cancel = 1
    };
};

#endif // ifndef __CheckBoxDlg_h
