// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  DialogDlg.h
  Thu Aug 22 23:58:28 1996

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __DialogDlg_h
#define __DialogDlg_h

class DialogDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[1075];

  enum
    {
         Widget_15 = 15,
          Widget_7 = 7,
              size = 14,
         Widget_23 = 23,
          Widget_9 = 9,
         Widget_10 = 10,
         Widget_19 = 19,
         Widget_21 = 21,
          Widget_2 = 2,
          Widget_3 = 3,
         Widget_28 = 28,
          filename = 1,
              name = 4,
        C_filename = 20,
            C_edit = 22,
        h_filename = 26,
            h_edit = 27,
             frame = 12,
             title = 6,
        killButton = 13,
                 X = 8,
                 Y = 11,
    validateCancel = 18,
        validateID = 24,
          cancelID = 25,
                ok = 17,
            cancel = 16
    };
};

#endif // ifndef __DialogDlg_h
