// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  LabelDlg.h
  Fri Mar 14 22:21:29 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __LabelDlg_h
#define __LabelDlg_h

class LabelDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[863];

  enum
    {
          group = 10,
      Widget_16 = 16,
      Widget_15 = 15,
       Widget_8 = 8,
       Widget_9 = 9,
      Widget_14 = 14,
      Widget_17 = 17,
           text = 3,
           name = 6,
      available = 4,
    labelHeight = 5,
           left = 7,
         center = 11,
          right = 12,
         margin = 13,
     normalFont = 18,
      fixedFont = 19,
        bigFont = 20,
             ok = 2,
         cancel = 1
    };
};

#endif // ifndef __LabelDlg_h
