// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  LoadDlg.h
  Fri Mar 14 23:57:45 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __LoadDlg_h
#define __LoadDlg_h

class LoadDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
    Widget_1 = 1,
        edit = 2,
          ok = 3,
      cancel = 4
    };
};

#endif // ifndef __LoadDlg_h
