// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  PrefsDlg.h
  Thu Aug 22 23:58:36 1996

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __PrefsDlg_h
#define __PrefsDlg_h

class PrefsDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[700];

  enum
    {
     Widget_15 = 15,
      Widget_1 = 1,
      Widget_3 = 3,
      Widget_7 = 7,
      Widget_9 = 9,
     Widget_12 = 12,
     Widget_13 = 13,
        granul = 2,
    drawGroups = 6,
           top = 8,
        bottom = 10,
         right = 14,
          left = 11,
            ok = 5,
        cancel = 4
    };
};

#endif // ifndef __PrefsDlg_h
