// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  RangeBarDlg.h
  Fri Mar 14 22:11:47 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __RangeBarDlg_h
#define __RangeBarDlg_h

class RangeBarDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[483];

  enum
    {
        group = 10,
     Widget_8 = 8,
     Widget_3 = 3,
    Widget_12 = 12,
         name = 6,
    available = 4,
     minValue = 16,
     maxValue = 9,
           ok = 2,
       cancel = 1
    };
};

#endif // ifndef __RangeBarDlg_h
