// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  TextBoxDlg.h
  Sun Apr 20 21:28:06 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __TextBoxDlg_h
#define __TextBoxDlg_h

class TextBoxDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
        group = 10,
     Widget_8 = 8,
     Widget_9 = 9,
     Widget_7 = 7,
         text = 3,
         name = 6,
    available = 4,
    fixedFont = 5,
         left = 11,
       center = 12,
        right = 13,
           ok = 2,
       cancel = 1
    };
};

#endif // ifndef __TextBoxDlg_h
