// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  ValueBarDlg.h
  Fri Mar 14 22:13:33 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __ValueBarDlg_h
#define __ValueBarDlg_h

class ValueBarDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[992];

  enum
    {
         group = 10,
      Widget_7 = 7,
      Widget_8 = 8,
      Widget_3 = 3,
     Widget_12 = 12,
     Widget_14 = 14,
     Widget_17 = 17,
     Widget_18 = 18,
     Widget_20 = 20,
     Widget_22 = 22,
          name = 6,
    linkWidget = 5,
     available = 4,
     fixedFont = 11,
      minValue = 16,
      maxValue = 9,
       nDigits = 13,
        minBar = 19,
        maxBar = 15,
     editWidth = 21,
            ok = 2,
        cancel = 1
    };
};

#endif // ifndef __ValueBarDlg_h
