// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  Dialog2Dlg.h
  Thu Aug 21 12:52:36 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __Dialog2Dlg_h
#define __Dialog2Dlg_h

class Dialog2Dlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
     Widget_1 = 1,
     Widget_2 = 2,
     Widget_3 = 3,
     Widget_4 = 4,
     Widget_5 = 5,
     Widget_6 = 6,
         edit = 7,
     Widget_8 = 8,
     Widget_9 = 9,
    Widget_10 = 10,
    Widget_11 = 11,
    Widget_12 = 12,
    Widget_13 = 13
    };
};

#endif // ifndef __Dialog2Dlg_h
