// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  Dialog3Dlg.h
  Mon Nov 25 18:04:42 1996

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __Dialog3Dlg_h
#define __Dialog3Dlg_h

class Dialog3Dlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[769];

  enum
    {
     Widget_16 = 16,
     Widget_17 = 17,
         group = 18,
     Widget_22 = 22,
     Widget_23 = 23,
     Widget_24 = 24,
     Widget_25 = 25,
          name = 19,
    linkWidget = 20,
     available = 21,
     itemsList = 26,
          item = 27,
    appendItem = 28,
    deleteItem = 29,
    insertItem = 30,
            ok = 2,
        cancel = 1
    };
};

#endif // ifndef __Dialog3Dlg_h
