// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  KBPopupDlg.h
  Sat Oct 25 16:45:33 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __KBPopupDlg_h
#define __KBPopupDlg_h

class KBPopupDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
         Widget_12 = 12,
         Widget_27 = 27,
         Widget_11 = 11,
         Widget_10 = 10,
            dialog = 5,
            widget = 6,
         centerAll = 17,
             prefs = 25,
       alignWidget = 20,
         available = 21,
         duplicate = 18,
      deleteWidget = 19,
       raiseWidget = 31,
       lowerWidget = 32,
      groupWidgets = 33,
    ungroupWidgets = 34,
              grid = 42,
       widgetsList = 23,
            create = 7,
         Widget_13 = 13,
         Widget_14 = 14,
         Widget_15 = 15,
              card = 16,
        insertCard = 22,
           newCard = 24,
        deleteCard = 26,
          editCard = 28,
         Widget_30 = 30
    };
};

#endif // ifndef __KBPopupDlg_h
