// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  KBWelcomeDlg.h
  Tue Oct 21 00:02:31 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __KBWelcomeDlg_h
#define __KBWelcomeDlg_h

class KBWelcomeDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
    Widget_19 = 19,
     Widget_2 = 2,
           b1 = 9,
           b2 = 5,
         edit = 10
    };
};

#endif // ifndef __KBWelcomeDlg_h
