// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  CameraDlg.h
  Wed Dec 18 22:25:42 1996

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __CameraDlg_h
#define __CameraDlg_h

class CameraDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[740];

  enum
    {
       Widget_2 = 2,
       Widget_6 = 6,
      Widget_10 = 10,
      Widget_11 = 11,
      Widget_12 = 12,
      Widget_18 = 18,
      Widget_13 = 13,
         object = 14,
      Widget_19 = 19,
        scale_x = 20,
        scale_z = 22,
       rotate_x = 3,
       rotate_z = 4,
    translate_x = 7,
    translate_y = 9,
          apply = 1
    };
};

#endif // ifndef __CameraDlg_h
