// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  LightDlg.h
  Sun Sep 21 15:45:10 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __LightDlg_h
#define __LightDlg_h

class LightDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
                Widget_14 = 14,
                Widget_22 = 22,
                Widget_34 = 34,
                 Widget_6 = 6,
                 Widget_7 = 7,
                Widget_35 = 35,
                Widget_36 = 36,
                 coneArea = 39,
                 Widget_3 = 3,
                Widget_11 = 11,
                colorArea = 16,
                  label_r = 18,
                  label_g = 19,
                  label_b = 20,
                     name = 8,
                 d_factor = 42,
                 g_factor = 48,
                     pool = 4,
                   update = 5,
                    apply = 15,
                  value_r = 21,
                  value_g = 23,
                  value_b = 24,
                radio_rgb = 43,
                radio_hsv = 44,
           direct_shading = 45,
                Widget_17 = 17,
       global_contributor = 46,
                Widget_47 = 47,
             extent_check = 25,
                   extent = 26,
       att_check_constant = 28,
             att_constant = 29,
         att_check_linear = 30,
               att_linear = 31,
      att_check_quadratic = 32,
            att_quadratic = 33,
                 rd_point = 1,
           rd_directional = 2,
             rd_spotlight = 13,
                   cutoff = 38,
                 exponent = 37,
                     list = 9,
                name_edit = 10,
                   rename = 12,
            adjust_cutoff = 41,
                Widget_40 = 40,
         generate_shadows = 49,
    radiosity_attenuation = 27,
       custom_attenuation = 50,
                Widget_51 = 51
    };
};

#endif // ifndef __LightDlg_h
