// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  ModesListDlg.h
  Fri Jan  2 16:44:41 1998

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __ModesListDlg_h
#define __ModesListDlg_h

class ModesListDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
             l_none = 22,
             l_undo = 23,
             l_walk = 24,
            l_orbit = 25,
             l_zoom = 26,
           l_select = 27,
             l_hide = 28,
           l_delete = 29,
         l_get_info = 30,
        l_duplicate = 31,
         l_reparent = 32,
      l_instantiate = 33,
        l_translate = 34,
    l_translate_xyz = 35,
        l_scale_xyz = 36,
            l_scale = 37,
           l_rotate = 38,
       l_rotate_xyz = 39,
           l_orient = 40,
     l_tag_polygons = 41,
     l_tag_vertices = 42,
          Widget_44 = 44,
          Widget_45 = 45,
    l_edit_material = 43,
               none = 21,
               undo = 18,
              orbit = 1,
               walk = 2,
               zoom = 3,
             select = 4,
            _delete = 5,
               hide = 6,
           get_info = 7,
          duplicate = 8,
        instantiate = 9,
           reparent = 10,
          translate = 11,
      translate_xyz = 12,
              scale = 13,
          scale_xyz = 14,
             rotate = 15,
         rotate_xyz = 16,
             orient = 17,
       tag_vertices = 19,
       tag_polygons = 20,
      edit_material = 46
    };
};

#endif // ifndef __ModesListDlg_h
