// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  PlainTextDlg.h
  Fri Mar  6 03:39:18 1998

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __PlainTextDlg_h
#define __PlainTextDlg_h

class PlainTextDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
         Widget_18 = 18,
         Widget_13 = 13,
            object = 14,
          Widget_5 = 5,
          Widget_2 = 2,
          Widget_9 = 9,
         Widget_11 = 11,
              font = 3,
    extrude_height = 8,
         Widget_15 = 15,
    total_polygons = 16,
         Widget_19 = 19,
              text = 6,
          set_font = 4,
         precision = 12,
             front = 17,
              back = 10,
              side = 7,
         Widget_21 = 21,
    reversed_sides = 20,
             apply = 1
    };
};

#endif // ifndef __PlainTextDlg_h
