// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  PoolDlg.h
  Sun Sep 21 02:39:01 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __PoolDlg_h
#define __PoolDlg_h

class PoolDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
    Widget_22 = 22,
     Widget_6 = 6,
    colorArea = 25,
    Widget_29 = 29,
      label_r = 31,
      label_g = 32,
      label_b = 33,
    Widget_11 = 11,
     Widget_3 = 3,
         name = 4,
      value_r = 26,
      value_g = 27,
      value_b = 28,
    radio_rgb = 1,
    radio_hsv = 2,
    intensity = 30,
         list = 9,
    name_edit = 10,
          add = 13,
       remove = 14,
       rename = 12,
       update = 5,
        apply = 15
    };
};

#endif // ifndef __PoolDlg_h
