// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  WelcomeDlg.h
  Mon Mar  9 23:23:16 1998

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __WelcomeDlg_h
#define __WelcomeDlg_h

class WelcomeDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
       Widget_19 = 19,
        Widget_2 = 2,
        Widget_3 = 3,
        Widget_4 = 4,
         version = 6,
             cpu = 7,
          vendor = 8,
        Widget_1 = 1,
       Widget_10 = 10,
       Widget_12 = 12,
              os = 13,
       Widget_14 = 14,
    introduction = 9,
         license = 5,
      modes_list = 11
    };
};

#endif // ifndef __WelcomeDlg_h
