// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  MaterialDlg.h
  Sun Sep 21 02:37:40 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __MaterialDlg_h
#define __MaterialDlg_h

class MaterialDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
              lighting = 160,
             emittance = 1,
               diffuse = 2,
              specular = 14,
            reflection = 15,
          transmission = 16,
             Widget_10 = 10,
            Widget_166 = 166,
             Widget_50 = 50,
            Widget_131 = 131,
             Widget_78 = 78,
             Widget_79 = 79,
            rename_mat = 12,
             Widget_28 = 28,
             Widget_46 = 46,
              Widget_3 = 3,
              Widget_5 = 5,
              Widget_7 = 7,
           object_name = 8,
             Widget_21 = 21,
                e_area = 24,
             e_r_label = 25,
             e_g_label = 26,
             e_b_label = 27,
             Widget_36 = 36,
             Widget_39 = 39,
             Widget_41 = 41,
             Widget_43 = 43,
          preview_area = 29,
          preview_type = 47,
        update_preview = 49,
             Widget_48 = 48,
             Widget_13 = 13,
        e_texture_name = 31,
           inherit_mat = 9,
              mat_list = 4,
             name_edit = 6,
            browse_mat = 33,
                   e_r = 17,
                   e_g = 18,
                   e_b = 19,
                 e_rgb = 22,
                 e_hsv = 23,
        e_color_factor = 20,
         e_use_texture = 30,
      e_browse_texture = 32,
        e_view_texture = 54,
           e_use_alpha = 45,
             e_xoffset = 37,
             e_yoffset = 38,
              e_xscale = 42,
              e_yscale = 44,
                change = 51,
                cancel = 52,
             Widget_34 = 34,
             Widget_35 = 35,
             Widget_40 = 40,
                d_area = 55,
             d_r_label = 56,
             d_g_label = 57,
             d_b_label = 58,
             Widget_59 = 59,
             Widget_60 = 60,
             Widget_61 = 61,
             Widget_62 = 62,
        d_texture_name = 63,
                   d_r = 64,
                   d_g = 65,
                   d_b = 66,
                 d_rgb = 67,
                 d_hsv = 68,
        d_color_factor = 69,
         d_use_texture = 70,
      d_browse_texture = 71,
        d_view_texture = 72,
           d_use_alpha = 73,
             d_xoffset = 74,
             d_yoffset = 75,
              d_xscale = 76,
              d_yscale = 77,
             Widget_80 = 80,
                s_area = 81,
             s_r_label = 82,
             s_g_label = 83,
             s_b_label = 84,
             Widget_85 = 85,
             Widget_86 = 86,
             Widget_87 = 87,
             Widget_88 = 88,
        s_texture_name = 89,
                   s_r = 90,
                   s_g = 91,
                   s_b = 92,
                 s_rgb = 93,
                 s_hsv = 94,
        s_color_factor = 95,
         s_use_texture = 96,
      s_browse_texture = 97,
        s_view_texture = 98,
           s_use_alpha = 99,
             s_xoffset = 100,
             s_yoffset = 101,
              s_xscale = 102,
              s_yscale = 103,
            Widget_104 = 104,
            Widget_105 = 105,
            Widget_106 = 106,
                r_area = 107,
             r_r_label = 108,
             r_g_label = 109,
             r_b_label = 110,
            Widget_111 = 111,
            Widget_112 = 112,
            Widget_113 = 113,
            Widget_114 = 114,
        r_texture_name = 115,
                   r_r = 116,
                   r_g = 117,
                   r_b = 118,
                 r_rgb = 119,
                 r_hsv = 120,
        r_color_factor = 121,
         r_use_texture = 122,
      r_browse_texture = 123,
        r_view_texture = 124,
           r_use_alpha = 125,
             r_xoffset = 126,
             r_yoffset = 127,
              r_xscale = 128,
              r_yscale = 129,
            Widget_130 = 130,
            Widget_132 = 132,
                t_area = 133,
             t_r_label = 134,
             t_g_label = 135,
             t_b_label = 136,
            Widget_137 = 137,
            Widget_138 = 138,
            Widget_139 = 139,
            Widget_140 = 140,
        t_texture_name = 141,
                   t_r = 142,
                   t_g = 143,
                   t_b = 144,
                 t_rgb = 145,
                 t_hsv = 146,
        t_color_factor = 147,
         t_use_texture = 148,
      t_browse_texture = 149,
        t_view_texture = 150,
           t_use_alpha = 151,
             t_xoffset = 152,
             t_yoffset = 153,
              t_xscale = 154,
              t_yscale = 155,
             Widget_11 = 11,
             shininess = 156,
            Widget_157 = 157,
               trans_n = 158,
         direct_shaded = 161,
    global_contributor = 162,
      generate_shadows = 163,
           get_shadows = 164
    };
};

#endif // ifndef __MaterialDlg_h
