// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  RendererOptionsDlg.h
  Tue Sep 23 21:44:49 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __RendererOptionsDlg_h
#define __RendererOptionsDlg_h

class RendererOptionsDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
               Widget_10 = 10,
                Widget_1 = 1,
               Widget_43 = 43,
               Widget_38 = 38,
              jpeg_group = 4,
              tiff_group = 11,
               Widget_33 = 33,
               Widget_16 = 16,
                      ok = 14,
                  cancel = 15,
               Widget_17 = 17,
                    xres = 18,
                    yres = 19,
               Widget_20 = 20,
               Widget_21 = 21,
           trace_shadows = 22,
    trace_global_shadows = 23,
               ray_depth = 24,
                Widget_2 = 2,
                Widget_3 = 3,
                Widget_5 = 5,
                Widget_6 = 6,
                location = 7,
             directories = 8,
                   files = 9,
               selection = 12,
               colorArea = 13,
               radio_hsv = 25,
               radio_rgb = 26,
                 value_r = 27,
                 value_g = 28,
                 value_b = 29,
                 label_b = 30,
                 label_g = 31,
                 label_r = 32,
       trace_reflections = 34,
     trace_transmissions = 35,
         constrain_ratio = 36,
                  ratios = 37,
               Widget_44 = 44,
               Widget_46 = 46,
             write_image = 39,
                 formats = 45,
            jpeg_quality = 47,
        progressive_jpeg = 48,
           compress_tiff = 49,
               Widget_40 = 40,
           default_gamma = 41,
            custom_gamma = 42,
                   gamma = 50,
                    beep = 51
    };
};

#endif // ifndef __RendererOptionsDlg_h
