// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  SceneInfoDlg.h
  Thu Aug  7 16:01:59 1997

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __SceneInfoDlg_h
#define __SceneInfoDlg_h

class SceneInfoDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
     Widget_4 = 4,
     Widget_2 = 2,
    sceneName = 3,
        close = 11,
     Widget_5 = 5,
    Widget_13 = 13,
     Widget_7 = 7,
     Widget_8 = 8,
     Widget_9 = 9,
    Widget_10 = 10,
         list = 1
    };
};

#endif // ifndef __SceneInfoDlg_h
