// This file is part of Moonlight Creator
//   Copyright (C) 1996-1998  Stephane Rehel
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

/*
  SelectTTFontDlg.h
  Sun Mar  8 04:16:33 1998

  Automatically generated by kBuilder
  Stephane Rehel, August 1996
*/

#ifndef __SelectTTFontDlg_h
#define __SelectTTFontDlg_h

class SelectTTFontDlg
{
public:
  static const int width;
  static const int height;
  static const unsigned char data[];

  enum
    {
        Widget_7 = 7,
        Widget_1 = 1,
       Widget_13 = 13,
           fonts = 3,
              ok = 16,
          cancel = 15,
        Widget_4 = 4,
     new_reposit = 5,
             add = 6,
            save = 8,
          remove = 9,
    preview_text = 11,
         preview = 12,
         reposit = 2
    };
};

#endif // ifndef __SelectTTFontDlg_h
